### ISSUE TITLE
我有一个问题？

### ISSUE THREAD

**Issue by JeffersonHuang** [dengyuanzhi/SerialProject#1]
忒修斯的船上的木头被逐渐替换 直到所有的木头都不是原来的木头 那这艘船还是原来的那艘船吗？

**Comment by JeffersonHuang** [comment]
https://app.gitbook.com/invite/pluto-3?invite=-LtUW7KutdeoGPsc5IzR

________________________________
发件人: Agonila <notifications@github.com>
发送时间: 2019年11月11日 22:17
收件人: dengyuanzhi/SerialProject <SerialProject@noreply.github.com>
抄送: Jankin <Archkernel@outlook.com>; Author <author@noreply.github.com>
主题: Re: [dengyuanzhi/SerialProject] 我有一个问题？ (#1)


Closed #1<https://github.com/dengyuanzhi/SerialProject/issues/1>.

―

**Comment by JingYuLuoer** [comment]
yes
